/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#16130e",
        "on-primary-container": "#522900",
        "secondary-fixed": "#ffdfa0",
        "on-secondary-fixed": "#261a00",
        "on-primary": "#4d2600",
        "on-secondary": "#402d00",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1f1b16",
        "inverse-surface": "#eae1d8",
        "tertiary-fixed": "#ffdbcd",
        "tertiary-container": "#ec7e4b",
        "on-primary-fixed": "#2f1500",
        primary: "#ffb77e",
        "on-secondary-fixed-variant": "#5c4300",
        "inverse-on-surface": "#34302a",
        "on-surface": "#eae1d8",
        "surface-container": "#231f1a",
        "on-primary-fixed-variant": "#6e3900",
        "inverse-primary": "#914c00",
        "on-tertiary-container": "#5e2000",
        "surface-container-highest": "#38342e",
        "surface-dim": "#16130e",
        "surface-variant": "#38342e",
        "on-background": "#eae1d8",
        "tertiary-fixed-dim": "#ffb596",
        tertiary: "#ffb596",
        "on-surface-variant": "#dcc2b0",
        "on-tertiary-fixed-variant": "#7d2d00",
        "secondary-container": "#c59300",
        secondary: "#f6be39",
        "surface-container-lowest": "#110e09",
        "surface-tint": "#ffb77e",
        outline: "#a38c7c",
        "secondary-fixed-dim": "#f6be39",
        "outline-variant": "#554336",
        surface: "#16130e",
        "surface-container-high": "#2d2924",
        "primary-fixed": "#ffdcc3",
        "on-tertiary": "#581e00",
        "on-secondary-container": "#433000",
        "error-container": "#93000a",
        error: "#ffb4ab",
        "on-tertiary-fixed": "#360f00",
        "on-error": "#690005",
        "primary-fixed-dim": "#ffb77e",
        "primary-container": "#e8821a",
        "surface-bright": "#3d3833",
        parchment: {
          DEFAULT: "#f2e5c8",
          muted: "#e8d7b0",
        },
        gold: {
          DEFAULT: "#ffb77e",
          bright: "#ffccaa",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        unit: "8px",
        gutter: "24px",
        "container-max": "1200px",
        "section-gap": "120px",
      },
      fontFamily: {
        "display-lg": ["var(--font-newsreader)"],
        "body-lg": ["var(--font-literata)"],
        "headline-lg": ["var(--font-newsreader)"],
        "headline-md": ["var(--font-newsreader)"],
        caption: ["var(--font-literata)"],
        "body-md": ["var(--font-literata)"],
        "label-md": ["var(--font-newsreader)"],
        devanagari: ["var(--font-devanagari)"],
        cinzel: ["var(--font-cinzel)"],
        sans: ["var(--font-literata)", "sans-serif"],
        serif: ["var(--font-newsreader)", "serif"],
      },
      fontSize: {
        "display-lg": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
